
pipeline {
    agent any
    environment {
        JenkinsDockerGCRSecret = credentials('jenkins-docker-gcr-secret')
    }
    stages {
        stage ('git clone - master') {
            when {
                branch 'master'
            }
            steps{
                git branch: 'master',
                    credentialsId: 'Rohan-Github-Account-Credentials',
                    url: 'https://github.com/rohan-searce/python-app-with-azure-kubernetes.git'
            }
        }
        stage ('git clone - uat') {
            when {
                branch 'uat'
            }
            steps{
                git branch: 'uat',
                    credentialsId: 'Rohan-Github-Account-Credentials',
                    url: 'https://github.com/rohan-searce/python-app-with-azure-kubernetes.git'
            }
        }
        stage ('build admin service into docker image - master') {
            when {
                branch 'master'
            }
            steps {
                dir ('jenkins-app') {
                    sh 'cat $JenkinsDockerGCRSecret | docker login --username _json_key --password-stdin https://gcr.io'
                    sh 'docker build --file Dockerfile --tag gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:$BUILD_NUMBER --tag gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:latest .'
                    sh 'docker push gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:$BUILD_NUMBER'   
                    sh 'docker push gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:latest'   
                    sh 'docker image ls gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:$BUILD_NUMBER'
                    sh 'docker image ls gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:latest'
                    sh 'docker image rm gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:$BUILD_NUMBER'
                    sh 'docker image rm gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:latest'
                }
            }
        }
        stage ('build admin service into docker image - uat') {
            when {
                branch 'uat'
            }
            steps {
                dir ('jenkins-app') {
                    sh 'cat $JenkinsDockerGCRSecret | docker login --username _json_key --password-stdin https://gcr.io'
                    sh 'docker build --file Dockerfile --tag gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:$BUILD_NUMBER --tag gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:latest .'
                    sh 'docker push gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:$BUILD_NUMBER'   
                    sh 'docker push gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:latest'   
                    sh 'docker image ls gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:$BUILD_NUMBER'
                    sh 'docker image ls gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:latest'
                    sh 'docker image rm gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:$BUILD_NUMBER'
                    sh 'docker image rm gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:latest'  
                }
            }
        }
        stage ('deploy to kubernetes cluster - master') {
            when {
                branch 'master'
            }
            steps {
                sh 'kubectl --namespace jenkins-dev --cluster gke_searce-academy_us-central1-c_rohan-ci-cd-cluster set image deployment jenkins-app jenkins-app=gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:$BUILD_NUMBER'
            }
        }
        stage ('deploy to kubernetes cluster - uat') {
            when {
                branch 'uat'
            }
            steps {
                sh 'kubectl --namespace jenkins-uat --cluster gke_searce-academy_us-central1-c_rohan-ci-cd-cluster set image deployment jenkins-app jenkins-app=gcr.io/searce-academy/rohan-ci-cd/jenkinsapp:$BUILD_NUMBER'
            }
        }
    }
}

