apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsapp-cicd
  labels:
    name: jenkinsapp-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jenkinsapp-cicd
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: jenkinsapp-cicd
    spec:
      containers:
      - name: test
        image: gcr.io/searce-academy/rohan-ci-cd/jenkins-cicd/dev/jenkinsapp:latest
        imagePullPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: jenkinsapp-cicd
spec:
  selector:
    name: jenkinsapp-cicd
  ports:
    - name: port1
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jenkinsapp-cicd
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: jenkinsapp-cicd
  targetCPUUtilizationPercentage: 80
